name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test - ${{ matrix.environment }} - ${{ matrix.testSettings }}
    runs-on: ubuntu-latest
    concurrency: environment-${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - server1
          - server2
        testSettings:
          - Unit Tests
          - Integration Tests
          - User Tests
    steps:
      - run: |
          echo "Testing ${{ matrix.testSettings }} on ${{ matrix.environment }}"
          sleep 10
          echo "Done with ${{ matrix.testSettings }} on ${{ matrix.environment }}"
